
title: Ira's Data Site
description: Posts on data sets, data science, and data viz.

url: http://irarickman.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: irickman
   email: irickman@gmail.com

google_analytics: "UA-102182533-1"
